src/ReadJapanese/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    url(r'^$', 'ReadJapanese.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^adduser/', 'ReadJapanese.views.adduser', name='adduser'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'
                                        ''}, name='login'),
    url(r'^logout/$', 'ReadJapanese.views.logout_user', name='logout'),
    url(r'^kana/', include('kana.urls', namespace="kana")),
]

src/kana/urls.py
from django.conf.urls import url
from kana import views

urlpatterns = [
    # ex: /kana/hiragana/
    url(r'^hiragana/$', views.hiragana, name='hiragana'),
    # ex: /kana/katakana/
    url(r'^katakana/$', views.katakana, name='katakana'),
    # ex: /kana/test/
    url(r'^test/', views.test, name='test'),
    # ex: /kana/mnemonics_handler/
    url(r'^practice/(?P<type>[0-9]+)/$', views.practice, name='practice'),
    # ex: /kana/mnemonics_handler/
    url(r'^mnemonics_handler/$', views.mnemonics_handler, name='mnemonics_handler'),
    # ex: /kana/5/
    url(r'^(?P<kana_order>[0-9]+)/$', views.detail, name='detail'),
    # ex: /kana/5/results/
    url(r'^(?P<kana_order>[0-9]+)/results/$', views.results, name='results'),

    
]

src/master_the_jouyou/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    url(r'^$', 'master_the_jouyou.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^adduser/', 'master_the_jouyou.views.adduser', name='adduser'),
    url(r'^adduser_confirmation/', 'master_the_jouyou.views.adduser_confirmation', name='adduser_confirmation'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'
                                        ''}, name='login'),
    url(r'^logout/$', 'master_the_jouyou.views.logout_user', name='logout'),
    url(r'^kana/', include('kana.urls', namespace="kana")),
]

src/kana/models.py
from django.db import models
from django.contrib import admin

class kana(models.Model):
    kana_order = models.IntegerField(null=True, blank=True)
    kana = models.CharField(max_length=2)
    unicode = models.CharField(max_length=20, null=True, blank=True)
    pronunciation = models.CharField(max_length=10, null=True, blank=True)
    pronunciation_tip = models.CharField(max_length=200, null=True, blank=True)
    mnemonic = models.CharField(max_length=200, null=True, blank=True)
    comment = models.CharField(max_length=1000, null=True, blank=True)
    vowel_group = models.CharField(max_length=5, null=True, blank=True)
    consonant_group = models.CharField(max_length=5, null=True, blank=True)
    parent = models.CharField(max_length=2, null=True, blank=True)
    hiragana_equivalent = models.CharField(max_length=2, null=True, blank=True)


class combinations(models.Model):
    kana = models.CharField(max_length=10)
    pronunciation = models.CharField(max_length=10)
    pronunciation_tip = models.CharField(max_length=200, null=True, blank=True)
    vowel_group = models.CharField(max_length=5, null=True, blank=True)
    consonant_group = models.CharField(max_length=5, null=True, blank=True)
    
class word(models.Model):
    word = models.CharField(max_length=50)
    pronunciation = models.CharField(max_length=100, null=True, blank=True)
    translation = models.CharField(max_length=500)
    module = models.IntegerField(null=True, blank=True)
    section = models.IntegerField(null=True, blank=True)
    
#class derived_kana_inline(admin.StackedInline):
#    model = derived_kana
#    extra = 4
#
class kana_admin(admin.ModelAdmin):
    #    inlines = [derived_kana_inline]
    list_display = ('kana_order', 'kana', 'pronunciation')
    
class word_admin(admin.ModelAdmin):
    list_display = ('id', 'word', 'translation')
    
class combination_admin(admin.ModelAdmin):
    list_display = ('id', 'kana', 'pronunciation')
    
hiragana_sections = [
                        {'start':1, 'end':15, 'section': 1, 'name':"Hiragana 1 - 15"},
                        {'start':16, 'end':30, 'section': 2, 'name':"Hiragana 16 - 30"},
                        {'start':31, 'end':46, 'section': 3, 'name':"Hiragana 31 - 47"},    
                     ]

katakana_sections = [
                        {'start':47, 'end':61, 'section': 1, 'name':"Katakana 1 - 15"},
                        {'start':62, 'end':76, 'section': 2, 'name':"Katakana 16 - 30"},
                        {'start':77, 'end':94, 'section': 3, 'name':"Katakana 31 - 45"},  
                     ]


admin.site.register(kana, kana_admin)
admin.site.register(combinations, combination_admin)
admin.site.register(word, word_admin)

src/kana/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render, get_object_or_404
from kana.models import kana, combinations, hiragana_sections, katakana_sections, word
from account_manager.helpers import getSessionOrAccountData, \
                    setSessionOrAccountData, \
                    deleteSessionOrAccountData
import json, random
from django.utils.html import strip_tags
from kana.helpers import *
                    



def hiragana(request):
    # session management
    next_incomplete_section_found = False
    next_incomplete_section = None
    for i,section in enumerate(hiragana_sections):
        section_finished_key = "hiragana_section_" + str(i) + "_finished"
        section_char_id_key = "hiragana_section_" + str(i) + "_char_id"
        # if section_finished_key in request.session.keys():
        if getSessionOrAccountData(request, section_finished_key):
            hiragana_sections[i]['status'] = "complete"
        # elif section_char_id_key in request.session.keys():
        elif getSessionOrAccountData(request, section_char_id_key):
            hiragana_sections[i]['status'] = getSessionOrAccountData(request, section_char_id_key)
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
        else:
            hiragana_sections[i]['status'] = "not_started"
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
    #end session management
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    context = {'sections': hiragana_sections,
               'next_incomplete_section': next_incomplete_section,
               'logged_in': logged_in,
               'username': username,
               'module_name': "Hiragana",
               'module_number': 1}
    return render(request, 'kana/index.html', context)

def katakana(request):
    # session management
    next_incomplete_section_found = False
    next_incomplete_section = None
    for i,section in enumerate(katakana_sections):
        section_finished_key = "katakana_section_" + str(i) + "_finished"
        section_char_id_key = "katakana_section_" + str(i) + "_char_id"
        # if section_finished_key in request.session.keys():
        if getSessionOrAccountData(request, section_finished_key):
            katakana_sections[i]['status'] = "complete"
        # elif section_char_id_key in request.session.keys():
        elif getSessionOrAccountData(request, section_char_id_key):
            katakana_sections[i]['status'] = getSessionOrAccountData(request, section_char_id_key)
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
        else:
            katakana_sections[i]['status'] = "not_started"
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
    #end session management
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    context = {'sections': katakana_sections,
               'next_incomplete_section': next_incomplete_section,
               'logged_in': logged_in,
               'username': username,
               'module_name': "Katakana",
               'module_number': 2}
    return render(request, 'kana/index.html', context)

def detail(request, kana_order):
    # check login status
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    #get the requested kana object
    kana_record = kana.objects.get(kana_order=kana_order)
    #get any child kana objects
    modifications = kana.objects.filter(parent=kana_record.kana)
    # determine if katakana or hiragana
    if kana_record.kana_order <= hiragana_sections[-1]['end']:
        sections = hiragana_sections
        module_name="hiragana"
    else:
        sections = katakana_sections
        module_name="katakana"
    #set variables used for record navigation
    nextKana = kana_record.kana_order+1
    previousKana = kana_record.kana_order-1
    for i,section in enumerate(sections):
        if kana_record.kana_order >= section['start'] and kana_record.kana_order <=section['end']:
            section_index = i
            first_in_section = True if kana_record.kana_order == section['start'] else False
            last_in_section = True if kana_record.kana_order == section['end'] else False   
            section_name = section['name'] 
            section_name = "Hiragana Section " + str(section['section'])
            break
    section_start_id = sections[section_index]['start']
    section_end_id = sections[section_index]['end']
    section_kanas = kana.objects.filter(kana_order__gte=section_start_id, kana_order__lte=section_end_id).order_by('kana_order')
    if kana_record.kana_order == sections[-1]['end']:
        last_in_module = True
    else:
        last_in_module = False
    if kana_record.kana_order == sections[0]['start']:
        first_in_module = True
    else:
        first_in_module = False
    # session management
    section_finished_key = module_name + "_section_" + str(section_index) + "_finished"
    section_char_id_key = module_name + "_section_" + str(section_index) + "_char_id"
    if not section_finished_key in request.session.keys():
        if last_in_section:
            setSessionOrAccountData(request, section_finished_key, True)
            deleteSessionOrAccountData(request, section_char_id_key)
            module_finished = True
            for i,section in enumerate(sections):
                this_section_finished_key = module_name + "_section_" + str(i) + "_finished"
                # if not this_section_finished_key in request.session.keys():
                if not getSessionOrAccountData(request, this_section_finished_key):
                    module_finished = False
            if module_finished:
                setSessionOrAccountData(request, module_name + '_module_finished', True)
        elif not first_in_section:            
            setSessionOrAccountData(request, section_char_id_key, kana_record.kana_order)
            setSessionOrAccountData(request, module_name + '_module_started', True)
    user_mnemonic = getSessionOrAccountData(request, 'kana_mnemonic_' + str(kana_record.kana_order))
    # end session management
    # add lookup popovers to appropriate fields
    if module_name=="katakana":
        pronunciation = add_popovers(request, kana_record.hiragana_equivalent)
    else:
        pronunciation = kana_record.pronunciation
    context = {'kana': kana_record, 
               'nextKana': nextKana, 
               'previousKana': previousKana,
               'section_kanas': section_kanas, 
               'modifications': modifications,
               'section_index': section_index,
               'section': sections[section_index],
               'section_name': section_name,
               'module_name': module_name,
               'first_in_section': first_in_section,
               'last_in_section': last_in_section,
               'logged_in': logged_in,
               'username': username,
               'user_mnemonic': user_mnemonic,
               'last_in_module': last_in_module,
               'first_in_module': first_in_module,
               'pronunciation': pronunciation}
    return render(request, 'kana/detail.html', context)

def results(request, kana_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % kana_id)

def mnemonics_handler(request):
    if request.is_ajax():
        key = "kana_mnemonic_" + request.GET['kana_number']
        setSessionOrAccountData(request, 
                                key,
                                strip_tags(request.GET['mnemonics_text']))
        result = getSessionOrAccountData(request, key)
        if not result:
            kana_object = get_object_or_404(kana, pk=request.GET['kana_number'])
            result = kana_object.mnemonic
        return HttpResponse(json.dumps( {'mnemonics_text': result} ))

def test(request):
    return render(request, 'kana/test.html', None)

def practice(request, type):
    if int(type) == 4:
        x = random.randint(1,2)
    else:
        x = int(type)
    if x == 1:
        kana_record = kana.objects.order_by('?')[0]
        kana_link = get_kana_link(kana_record.kana)
        context = {'kana_record': kana_record,
                   'pronunciation': kana_record.mnemonic,
                   'translation': kana_record.pronunciation,
                   'kana_link': kana_link,
                   }
        return render(request, 'kana/flashcard.html', context)
    if x == 2:
        word_record = word.objects.order_by('?')[0]
        print(word_record.translation)
        word_table = practicify(request, word_record.word)
        # word_table = word_record.word
        print(len(word_record.word))
        extra_info = [word_record.translation]
        context = {'word_table': word_table,
                   'extra_info': extra_info,
                   }
        return render(request, 'kana/vocabulary.html', context)
    

            
        

src/kana/templates/core_shell.html
<!DOCTYPE html>
<html lang="en">
  
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- Optional theme -->
	<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
	<link rel="stylesheet" href="http://bootswatch.com/cerulean/bootstrap.min.css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <title>{% block title %}Master the Jo&#773;yo&#773;{% endblock %}</title>
    <style type="text/css">
	    body {
	    padding-top: 65px;
	    }
	    .popover-content {
		    font-size: 12px;
		}
		.popover-title  {
		    font-size: 20px;
		}
		.label-warning  {
		    background-color: #CCA300;
		}
		.top_right{
		    position: absolute;
		    top: 0;
		    right: 15px;
	    }
	    .top_left{
		    position: absolute;
		    top: 10px;
		    left: 25px;
	    }
	    {% block css %}{% endblock %}
    </style>
    <script type="text/javascript">
        {% block js %}{% endblock %}
	</script>
    
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Master the Jo&#773;yo&#773;</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Character Modules</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Practice <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'kana:practice' 1 %}">Flashcards</a></li>
                            <li><a href="{% url 'kana:practice' 2 %}">Vocabulary Practice</a></li>
                            <li><a href="#">Reading Practice</a></li>
                            <li><a href="{% url 'kana:practice' 4 %}">Mixed Practice</a></li>
                        </ul>
                    </li>
                    <li><a href="#">About</a></li>
                    <li class="dropdown">
                        {% if logged_in %}
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as {{ username }} <span class="caret"></span></a>
	                        <ul class="dropdown-menu" role="menu">
	                            <li><a href="{% url 'logout' %}">Log Out</a></li>
	                            <li><a href="#">Account Settings</a></li>
	                        </ul>
                        {% else %}
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
	                        <ul class="dropdown-menu" role="menu">
	                            <li><a href="{% url 'login' %}?next={% url 'home' %}">Log In</a></li>
	                            <li><a href="{% url 'adduser' %}">Create An Account</a></li>
	                        </ul>
                        {% endif %}
                    </li>
               </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-xs-12 col-sm-9">
                <div class="jumbotron">
		            <h1>
		                {% block header %} Enter Page Name {% endblock %}
		            </h1>
		            {% block content %} Enter Page Content {% endblock %}
	            </div> 
	            <p>
	                {% block links %} Enter Links {% endblock %} 
	            </p>
	        </div>
	        {% block right_navbar %} Enter Navigation {% endblock %}
	    </div>
    </div>  
</body>

</html>

src/kana/templates/home.html
{% extends "no_sidebar_shell.html" %}
{% load staticfiles %}

{% block header %}
	Master the Jo&#773;yo&#773;
{% endblock %}


{% block content %}
	<p>A Comprehensive System for Learning to Read Japanese</p>
{% endblock %}

{% block links %}
	<h2>Character Modules</h2>
	<a href="{% url 'kana:hiragana' %}" class="list-group-item">
		{% if hiragana_module_finished %}
			<span class="label label-success status"> complete &nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 1: <strong>Hiragana</strong>
		{% elif hiragana_module_started %}
			<span class="label label-warning status">incomplete</span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 1: <strong>Hiragana</strong>
			<span class="label label-success pull-right" style="font-size:14px">continue &raquo;</span>
		{% else %}
			<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 1: <strong>Hiragana</strong>
			<span class="label label-success pull-right" style="font-size:14px">start &raquo;</span>
		{% endif %}	
	</a>
	<a href="{% url 'kana:katakana' %}" class="list-group-item">
		{% if katakana_module_finished %}
			<span class="label label-success status"> complete &nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 2: <strong>Katakana</strong>
		{% elif katakana_module_started %}
			<span class="label label-warning status">incomplete</span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 2: <strong>Katakana</strong>
		{% else %}
			<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
			Module 2: <strong>Katakana</strong>
		{% endif %}	
	</a>
	<a href="#" class="list-group-item">
		<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
		Module 3: <strong>First 100 Kanji</strong>
	</a>
	<a href="#" class="list-group-item">
		<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
		Module 4: <strong>Beginner Kanji</strong>
	</a>
	<a href="#" class="list-group-item">
		<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
		Module 5: <strong>Intermediate Kanji</strong>
	</a>
	<a href="#" class="list-group-item">
		<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
		Module 6: <strong>Advanced Kanji</strong>
	</a>
	<a href="#" class="list-group-item">
		<span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
		Module 7: <strong>Rare Kanji</strong>
	</a>
{% endblock %}

src/kana/templates/no_sidebar_shell.html
{% extends "core_shell.html" %}

{% block right_navbar %}

{% endblock %}

src/kana/templates/right_sidebar_shell.html
{% extends "core_shell.html" %}


{% block right_navbar %}
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
        <div class="list-group">
            {% block section_navigation %} Enter navigation {% endblock %}
        </div>
    </div>
{% endblock %}