src/ReadJapanese/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    url(r'^$', 'ReadJapanese.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^adduser/', 'ReadJapanese.views.adduser', name='adduser'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'
                                        ''}, name='login'),
    url(r'^logout/$', 'ReadJapanese.views.logout_user', name='logout'),
    url(r'^kana/', include('kana.urls', namespace="kana")),
]

src/kana/urls.py
from django.conf.urls import url
from kana import views

urlpatterns = [
    # ex: /kana/hiragana/
    url(r'^hiragana/$', views.hiragana, name='hiragana'),
    # ex: /kana/katakana/
    url(r'^katakana/$', views.katakana, name='katakana'),
    # ex: /kana/test/
    url(r'^test/', views.test, name='test'),
    # ex: /kana/mnemonics_handler/
    url(r'^practice/(?P<type>[0-9]+)/$', views.practice, name='practice'),
    # ex: /kana/mnemonics_handler/
    url(r'^mnemonics_handler/$', views.mnemonics_handler, name='mnemonics_handler'),
    # ex: /kana/5/
    url(r'^(?P<kana_order>[0-9]+)/$', views.detail, name='detail'),
    # ex: /kana/5/results/
    url(r'^(?P<kana_order>[0-9]+)/results/$', views.results, name='results'),

    
]

src/master_the_jouyou/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Examples:
    url(r'^$', 'master_the_jouyou.views.index', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^adduser/', 'master_the_jouyou.views.adduser', name='adduser'),
    url(r'^adduser_confirmation/', 'master_the_jouyou.views.adduser_confirmation', name='adduser_confirmation'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'
                                        ''}, name='login'),
    url(r'^logout/$', 'master_the_jouyou.views.logout_user', name='logout'),
    url(r'^kana/', include('kana.urls', namespace="kana")),
]

src/kana/models.py
from django.db import models
from django.contrib import admin

class kana(models.Model):
    kana_order = models.IntegerField(null=True, blank=True)
    kana = models.CharField(max_length=2)
    unicode = models.CharField(max_length=20, null=True, blank=True)
    pronunciation = models.CharField(max_length=10, null=True, blank=True)
    pronunciation_tip = models.CharField(max_length=200, null=True, blank=True)
    mnemonic = models.CharField(max_length=200, null=True, blank=True)
    comment = models.CharField(max_length=1000, null=True, blank=True)
    vowel_group = models.CharField(max_length=5, null=True, blank=True)
    consonant_group = models.CharField(max_length=5, null=True, blank=True)
    parent = models.CharField(max_length=2, null=True, blank=True)
    hiragana_equivalent = models.CharField(max_length=2, null=True, blank=True)


class combinations(models.Model):
    kana = models.CharField(max_length=10)
    pronunciation = models.CharField(max_length=10)
    pronunciation_tip = models.CharField(max_length=200, null=True, blank=True)
    vowel_group = models.CharField(max_length=5, null=True, blank=True)
    consonant_group = models.CharField(max_length=5, null=True, blank=True)
    
class word(models.Model):
    word = models.CharField(max_length=50)
    pronunciation = models.CharField(max_length=100, null=True, blank=True)
    translation = models.CharField(max_length=500)
    module = models.IntegerField(null=True, blank=True)
    section = models.IntegerField(null=True, blank=True)
    
#class derived_kana_inline(admin.StackedInline):
#    model = derived_kana
#    extra = 4
#
class kana_admin(admin.ModelAdmin):
    #    inlines = [derived_kana_inline]
    list_display = ('kana_order', 'kana', 'pronunciation')
    
class word_admin(admin.ModelAdmin):
    list_display = ('id', 'word', 'translation')
    
class combination_admin(admin.ModelAdmin):
    list_display = ('id', 'kana', 'pronunciation')
    
hiragana_sections = [
                        {'start':1, 'end':15, 'section': 1, 'name':"Hiragana 1 - 15"},
                        {'start':16, 'end':30, 'section': 2, 'name':"Hiragana 16 - 30"},
                        {'start':31, 'end':46, 'section': 3, 'name':"Hiragana 31 - 47"},    
                     ]

katakana_sections = [
                        {'start':47, 'end':61, 'section': 1, 'name':"Katakana 1 - 15"},
                        {'start':62, 'end':76, 'section': 2, 'name':"Katakana 16 - 30"},
                        {'start':77, 'end':94, 'section': 3, 'name':"Katakana 31 - 45"},  
                     ]


admin.site.register(kana, kana_admin)
admin.site.register(combinations, combination_admin)
admin.site.register(word, word_admin)

src/kana/views.py
from django.shortcuts import HttpResponse
from django.shortcuts import render, get_object_or_404
from kana.models import kana, combinations, hiragana_sections, katakana_sections, word
from account_manager.helpers import getSessionOrAccountData, \
                    setSessionOrAccountData, \
                    deleteSessionOrAccountData
import json, random
from django.utils.html import strip_tags
from kana.helpers import *
                    



def hiragana(request):
    # session management
    next_incomplete_section_found = False
    next_incomplete_section = None
    for i,section in enumerate(hiragana_sections):
        section_finished_key = "hiragana_section_" + str(i) + "_finished"
        section_char_id_key = "hiragana_section_" + str(i) + "_char_id"
        # if section_finished_key in request.session.keys():
        if getSessionOrAccountData(request, section_finished_key):
            hiragana_sections[i]['status'] = "complete"
        # elif section_char_id_key in request.session.keys():
        elif getSessionOrAccountData(request, section_char_id_key):
            hiragana_sections[i]['status'] = getSessionOrAccountData(request, section_char_id_key)
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
        else:
            hiragana_sections[i]['status'] = "not_started"
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
    #end session management
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    context = {'sections': hiragana_sections,
               'next_incomplete_section': next_incomplete_section,
               'logged_in': logged_in,
               'username': username,
               'module_name': "Hiragana",
               'module_number': 1}
    return render(request, 'kana/index.html', context)

def katakana(request):
    # session management
    next_incomplete_section_found = False
    next_incomplete_section = None
    for i,section in enumerate(katakana_sections):
        section_finished_key = "katakana_section_" + str(i) + "_finished"
        section_char_id_key = "katakana_section_" + str(i) + "_char_id"
        # if section_finished_key in request.session.keys():
        if getSessionOrAccountData(request, section_finished_key):
            katakana_sections[i]['status'] = "complete"
        # elif section_char_id_key in request.session.keys():
        elif getSessionOrAccountData(request, section_char_id_key):
            katakana_sections[i]['status'] = getSessionOrAccountData(request, section_char_id_key)
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
        else:
            katakana_sections[i]['status'] = "not_started"
            if not next_incomplete_section_found:
                next_incomplete_section = section['section']
                next_incomplete_section_found = True
    #end session management
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    context = {'sections': katakana_sections,
               'next_incomplete_section': next_incomplete_section,
               'logged_in': logged_in,
               'username': username,
               'module_name': "Katakana",
               'module_number': 2}
    return render(request, 'kana/index.html', context)

def detail(request, kana_order):
    # check login status
    if request.user.is_authenticated():
        logged_in = True
        username = request.user.username
    else:
        logged_in = False
        username = None
    #get the requested kana object
    kana_record = kana.objects.get(kana_order=kana_order)
    #get any child kana objects
    modifications = kana.objects.filter(parent=kana_record.kana)
    # determine if katakana or hiragana
    if kana_record.kana_order <= hiragana_sections[-1]['end']:
        sections = hiragana_sections
        module_name="hiragana"
    else:
        sections = katakana_sections
        module_name="katakana"
    #set variables used for record navigation
    nextKana = kana_record.kana_order+1
    previousKana = kana_record.kana_order-1
    for i,section in enumerate(sections):
        if kana_record.kana_order >= section['start'] and kana_record.kana_order <=section['end']:
            section_index = i
            first_in_section = True if kana_record.kana_order == section['start'] else False
            last_in_section = True if kana_record.kana_order == section['end'] else False   
            section_name = section['name'] 
            section_name = "Hiragana Section " + str(section['section'])
            break
    section_start_id = sections[section_index]['start']
    section_end_id = sections[section_index]['end']
    section_kanas = kana.objects.filter(kana_order__gte=section_start_id, kana_order__lte=section_end_id).order_by('kana_order')
    if kana_record.kana_order == sections[-1]['end']:
        last_in_module = True
    else:
        last_in_module = False
    if kana_record.kana_order == sections[0]['start']:
        first_in_module = True
    else:
        first_in_module = False
    # session management
    section_finished_key = module_name + "_section_" + str(section_index) + "_finished"
    section_char_id_key = module_name + "_section_" + str(section_index) + "_char_id"
    if not section_finished_key in request.session.keys():
        if last_in_section:
            setSessionOrAccountData(request, section_finished_key, True)
            deleteSessionOrAccountData(request, section_char_id_key)
            module_finished = True
            for i,section in enumerate(sections):
                this_section_finished_key = module_name + "_section_" + str(i) + "_finished"
                # if not this_section_finished_key in request.session.keys():
                if not getSessionOrAccountData(request, this_section_finished_key):
                    module_finished = False
            if module_finished:
                setSessionOrAccountData(request, module_name + '_module_finished', True)
        elif not first_in_section:            
            setSessionOrAccountData(request, section_char_id_key, kana_record.kana_order)
            setSessionOrAccountData(request, module_name + '_module_started', True)
    user_mnemonic = getSessionOrAccountData(request, 'kana_mnemonic_' + str(kana_record.kana_order))
    # end session management
    # add lookup popovers to appropriate fields
    if module_name=="katakana":
        pronunciation = add_popovers(request, kana_record.hiragana_equivalent)
    else:
        pronunciation = kana_record.pronunciation
    context = {'kana': kana_record, 
               'nextKana': nextKana, 
               'previousKana': previousKana,
               'section_kanas': section_kanas, 
               'modifications': modifications,
               'section_index': section_index,
               'section': sections[section_index],
               'section_name': section_name,
               'module_name': module_name,
               'first_in_section': first_in_section,
               'last_in_section': last_in_section,
               'logged_in': logged_in,
               'username': username,
               'user_mnemonic': user_mnemonic,
               'last_in_module': last_in_module,
               'first_in_module': first_in_module,
               'pronunciation': pronunciation}
    return render(request, 'kana/detail.html', context)

def results(request, kana_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % kana_id)

def mnemonics_handler(request):
    if request.is_ajax():
        key = "kana_mnemonic_" + request.GET['kana_number']
        setSessionOrAccountData(request, 
                                key,
                                strip_tags(request.GET['mnemonics_text']))
        result = getSessionOrAccountData(request, key)
        if not result:
            kana_object = get_object_or_404(kana, pk=request.GET['kana_number'])
            result = kana_object.mnemonic
        return HttpResponse(json.dumps( {'mnemonics_text': result} ))

def test(request):
    return render(request, 'kana/test.html', None)

def practice(request, type):
    if int(type) == 4:
        x = random.randint(1,2)
    else:
        x = int(type)
    if x == 1:
        kana_record = kana.objects.order_by('?')[0]
        kana_link = get_kana_link(kana_record.kana)
        context = {'kana_record': kana_record,
                   'pronunciation': kana_record.mnemonic,
                   'translation': kana_record.pronunciation,
                   'kana_link': kana_link,
                   }
        return render(request, 'kana/flashcard.html', context)
    if x == 2:
        word_record = word.objects.order_by('?')[0]
        print(word_record.translation)
        word_table = practicify(request, word_record.word)
        # word_table = word_record.word
        print(len(word_record.word))
        extra_info = [word_record.translation]
        context = {'word_table': word_table,
                   'extra_info': extra_info,
                   }
        return render(request, 'kana/vocabulary.html', context)
    

            
        

src/kana/templates/kana/detail.html
{% extends "right_sidebar_shell.html" %}
{% load staticfiles %}

{% block title %}
	[ {{ kana.kana }} ] Master the Jo&#773;yo&#773;
{% endblock %}

{% block js %}
		
//ajax for mnemonics change
$(function() {

    $("#mnemonics_button").click(function() {
        var data = $('#mnemonics_form').serialize();
        $('#mnemonic').html('<img src="{% static "img/waiting.gif" %}" width=30 height=30>');
        $.get("{% url 'kana:mnemonics_handler' %}", data, myHandler)
        return false;
    });
    
    function myHandler(data)  {
        var obj = jQuery.parseJSON( data );
        $('#mnemonic').html('<em>Mnemonic:</em> ' + obj.mnemonics_text + '<br>');
    }
    
    $('.add_popover').popover({ html : true });
    
});

//action on left arrow (37) and right arrow (39) keypress
$(document).keydown(function(e) {
		    if (e.which == 37) { 
		       {% if not first_in_section %}
	               window.location = "{% url 'kana:detail' previousKana %}";
	           {% elif module_name == 'hiragana' %}
	               window.location = "{% url 'kana:hiragana' %}";
	           {% else %}
	               window.location = "{% url 'kana:katakana' %}";
	           {% endif %}
		       e.preventDefault();
		       return false;
		    }	
		    if (e.which == 39) { 
		       {% if not last_in_section %}
				    window.location = "{% url 'kana:detail' nextKana %}";
			   {% elif module_name == 'hiragana' %}
	               window.location = "{% url 'kana:hiragana' %}";
	           {% else %}
	               window.location = "{% url 'kana:katakana' %}";
			   {% endif %}
		       e.preventDefault();
		       return false;
		    }
		});




{% endblock %}


{% block header %}
<span style="color:#CC5200;font-size:100px;">
	{{ kana.kana }}
</span>
{% endblock %}



{% block content %}
    <div class="top_left">
	    {% if not first_in_section %}
		    <a href="{% url 'kana:detail' previousKana %}">&laquo; Previous character</a> &nbsp;&nbsp;&nbsp;&nbsp;
		{% elif not first_in_module %}
		    <a href="{% url 'kana:detail' previousKana %}" style="color:#EB9316;" role="button">
		    	&lt;&lt;&lt; Previous Section</a> &nbsp;&nbsp;&nbsp;&nbsp;
		{% endif %}
    </div>
    <div class="top_right">
	    {% if not last_in_section %}
	    	<a href="{% url 'kana:detail' nextKana %}" class="btn btn-primary" role="button">Next character &raquo;</a>
	    {% elif not last_in_module %}
		    <a href="{% url 'kana:detail' nextKana %}" class="btn btn-warning" role="button">Next Section &raquo;</a>
		{% endif %}
    </div>
    
    
	<p>
	<span style="font-size:30px">
		[ <strong>{% autoescape off %}{{ pronunciation }}{% endautoescape %}</strong> ]
	</span>&nbsp;&nbsp;
	{% if kana.pronunciation_tip %}
	    {{ kana.pronunciation_tip }}
	{% endif %}
    {% if modifications %}
    <br /><em>Modifications:</em>
    {% for kana in modifications %}
        <strong><span style="color:#CC5200;font-size:30px;">{{ kana.kana }}</span></strong>  
        ({{kana.pronunciation }})&nbsp;&nbsp;&nbsp;&nbsp;
    {% endfor %}
    {% endif %}	 
        </p>
    <span id="mnemonic">
	    {% if user_mnemonic %}
	        <em>Mnemonic:</em> {{ user_mnemonic }}<br>
	    {% elif kana.mnemonic %}
	        <em>Mnemonic:</em> {{ kana.mnemonic }}<br>
	    {% endif %}
    </span>
    {% if kana.comment %}
        <br /><div class="alert alert-info" role="alert"><strong>note:</strong> {{ kana.comment }}</div>
    {% endif %}
	<hr>
	<a href="#" data-toggle="collapse" data-target="#demo">Show More</a>
    <div id="demo" class="collapse">
    <em>Add/Change mnemonic:</em>
	    <form name="mnemonics_form" id="mnemonics_form" action="">
	        <input type="hidden" name="kana_number" value="{{ kana.kana_order }}" />
	        <textarea name="mnemonics_text" id="mnemonics_text" rows="4" cols="50" maxlength="500"
	            >{% if user_mnemonic %}{{ user_mnemonic }}{% endif %}</textarea>
	        <input type="submit" name="submit" class="button" id="mnemonics_button" value="Submit" />
	    </form>
    </div>
{% endblock %}



{% block section_navigation %}
   {% if section_kanas %}
       <span class="list-group-item active" style="background-color:#033c73">{{ section_name }}</span>
    {% for section_kana in section_kanas %}
        {% if section_kana.kana_order == kana.kana_order %}
            <a href="{% url 'kana:detail' section_kana.kana_order %}" class="list-group-item active">
                {{ section_kana.kana_order }}. <strong>[ {{ section_kana.kana }} ]</strong>
            </a>
        {% else %}
            <a href="{% url 'kana:detail' section_kana.kana_order %}" class="list-group-item">
                {{ section_kana.kana_order }}. <strong>[ {{ section_kana.kana }} ]</strong>
            </a>
        {% endif %}
    {% endfor %}
{% else %}
    <p>No kana are available.</p>
{% endif %}
{% endblock %}



{% block links %}
    {% if module_name == 'hiragana' %}
	    <a href="{% url 'kana:hiragana' %}" class="btn btn-lg btn-link" role="button">
	        &lt;&lt;&lt; Back to Hiragana Module
	    </a>
    {% else %}
	    <a href="{% url 'kana:katakana' %}" class="btn btn-lg btn-link" role="button">
	        &lt;&lt;&lt; Back to Katakana Module
	    </a>
    {% endif %}
{% endblock %}

src/kana/templates/kana/flashcard.html
{% extends "no_sidebar_shell.html" %}
{% load staticfiles %}

{% block title %}
	[ Practice ] Master the Jo&#773;yo&#773;
{% endblock %}

{% block css %}
	.pronunciation {
	    font-size: 20px;
	    text-align: center;
	    visibility: hidden;
	}
	.char  {
	    font-size: 100px;
	    text-align: center;
	}
    #translation  {
    	visibility: hidden;
    }
	.center_table {
	  width: 100%;
	}
	#flashcard  {
	    padding: 5px;
	    margin: 20px;
	    border: black solid 2px;
	    text-align: center;
	}
	#kana_cell  {
	    font-size: 70px;
	    text-align: left;
	    color:#CC5200;
	}
	#info_cell  {
	    visibility: hidden;
	}
	#pronunciation  {
	    font-size: 20px;	
	}
	.padded td {
	    padding: 20px;
	}
	.center_align  {
	    text-align: center;
	}
{% endblock %}


{% block js %}
		
//ajax for mnemonics change
$(function() {
    
    $('.add_popover').popover({ html : true });
    
    $('#show_element').click(function() {
        if ( $('#show_element').html() == 'show answer' )  {
            $('#info_cell').css('visibility', 'visible');
            $('#show_element').html('next question &raquo;');
        } else {
            location.reload();
        }
        
    });
    
});

//action on left arrow (37) and right arrow (39) keypress
$(document).keydown(function(e) {
		    if (e.which == 39) { 
		       $('#show_element').click();
		       e.preventDefault();
		       return false;
		    }
		});


{% endblock %}


{% block header %}Vocabulary Practice{% endblock %}

{% block content %}
    <div class="top_left">
	    <a href="#">&laquo; Previous question</a>
    </div>
    <div class="top_right">
     	<a href="#" class="btn btn-primary" role="button">Next question &raquo;</a>
    </div>
{% endblock %}



{% block links %}
	<div class="col-lg-3">&nbsp;</div>
	<div class="col-lg-6 center_align">
	    <div id="flashcard">
	    <table class="center_table padded">
	        <tr>
	            <td id="kana_cell">
	                {{ kana_record.kana }}
	            </td>
	            <td id="info_cell">
	                <span id="pronunciation">[ {{ kana_record.pronunciation }} ]</span><br>
	                {% if kana_record.pronunciation_tip %}
	                    {{ kana_record.pronunciation_tip }}<br>
	                {% endif %}
	                {% if kana_record.mnemonic %}
	                    <em>mnemonic:</em> {{ kana_record.mnemonic }}<br>
	                {% endif %}
	                <br><a href="{% url 'kana:detail' kana_link %}">More...</a>
	            </td>
	        </tr>
	    </table>	  
	    </div> 
	    <button id="show_element" class="btn btn-success btn-sm" role="button">show answer</button>
	</div>
	<div class="col-lg-3">&nbsp;</div>
{% endblock %}

src/kana/templates/kana/index.html
{% extends "no_sidebar_shell.html" %}
{% load staticfiles %}

{% block title %}
	{{ module_name }}: Master the Jo&#773;yo&#773;
{% endblock %}

{% block header %}
	Module {{ module_number }}: {{ module_name }}
{% endblock %}


{% block content %}
	{% if sections %}
		{% for section in sections %}
		    {% if section.status == "complete" or section.status == "not_started" %}
			    <a href="{% url 'kana:detail' section.start %}" class="list-group-item">
			{% else %}
			    <a href="{% url 'kana:detail' section.status %}" class="list-group-item">
			{% endif %}
				{% if section.status == "complete" %}
     	    		<span class="label label-success status"> complete &nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;
     	    	{% elif section.status == "not_started" %}
     	    	    <span class="label label-danger status">not started </span>&nbsp;&nbsp;&nbsp;&nbsp;
     	    	{% else %}
     	    	    <span class="label label-warning status">incomplete</span>&nbsp;&nbsp;&nbsp;&nbsp;
     	    	{% endif %}
     	    	Section {{ section.section }}: {{ section.name }}
     	    	{% if next_incomplete_section == section.section %}
     	    	    {% if section.status == "not_started" %}
     	    	    	<span class="label label-success pull-right" style="font-size:14px">start &raquo;</span>
     	    	    {% else %}
     	    	    	<span class="label label-success pull-right" style="font-size:14px">continue &raquo;</span>
     	    	    {% endif %}
     	    	{% endif %}
     	    </a>
		{% endfor %}
    {% else %}
        <p>No kana are available.</p>
    {% endif %}
{% endblock %}

{% block links %}
    <a href="{% url 'home' %}" class="btn btn-lg btn-link" role="button">&lt;&lt;&lt; Back to All Modules</a></button>
{% endblock %}

src/kana/templates/kana/practice.html
{% extends "right_sidebar_shell.html" %}
{% load staticfiles %}

{% block title %}
	[ Practice ] Master the Jo&#773;yo&#773;
{% endblock %}

{% block css %}
	.pronunciation {
	    font-size: 20px;
	    text-align: center;
	    visibility: hidden;
	}
	.char  {
	    font-size: 70px;
	    text-align: center;
	}
    #translation  {
    	visibility: hidden;
    }
	.center_table {
	  margin: 0 auto !important;
	  float: none !important;
	}
{% endblock %}


{% block js %}
		
//ajax for mnemonics change
$(function() {
    
    $('.add_popover').popover({ html : true });
    
    $('#show_element').click(function() {
        if ( $('#show_element').html() == 'show answer' )  {
            $('.pronunciation').css('visibility', 'visible');
            $('#translation').css('visibility', 'visible');
            $('#show_element').html('next question &raquo;');
        } else {
            location.reload();
        }
        
    });
    
});

//action on left arrow (37) and right arrow (39) keypress
$(document).keydown(function(e) {
		    if (e.which == 39) { 
		       $('#show_element').click();
		       e.preventDefault();
		       return false;
		    }
		});


{% endblock %}


{% block header %}Vocabulary Practice{% endblock %}

{% block content %}
    <div class="top_left">
	    <a href="#">&laquo; Previous question</a>
    </div>
    <div class="top_right">
     	<a href="#" class="btn btn-primary" role="button">Next question &raquo;</a>
    </div>
{% endblock %}



{% block links %}
	<div class="text-center">
	   {% autoescape off %}{{ mystr }}{% endautoescape %}
	   <div id="translation">
	       <em>pronunciation:</em> {{ pronunciation }}<br />
	       <em>meaning:</em> {{ translation }}
	   </div><br /><br />
	   <button id="show_element" class="btn btn-success btn-sm" role="button">show answer</button>
	</div>
{% endblock %}

src/kana/templates/kana/vocabulary.html
{% extends "no_sidebar_shell.html" %}
{% load staticfiles %}

{% block title %}
	[ Practice ] Master the Jo&#773;yo&#773;
{% endblock %}

{% block css %}
	.pronunciation {
	    font-size: 20px;
	    text-align: center;
	    visibility: hidden;
	}
	.char  {
	    font-size: 70px;
	    text-align: center;
	}
    #translation  {
    	visibility: hidden;
    }
	.center_table {
	  margin: 0 auto !important;
	  float: none !important;
	}
	
{% endblock %}


{% block js %}
		
//ajax for mnemonics change
$(function() {
    
    $('.add_popover').popover({ html : true });
    
    $('#show_element').click(function() {
        if ( $('#show_element').html() == 'show answer' )  {
            $('.pronunciation').css('visibility', 'visible');
            $('#translation').css('visibility', 'visible');
            $('#show_element').html('next question &raquo;');
        } else {
            location.reload();
        }
        
    });
    
});

//action on left arrow (37) and right arrow (39) keypress
$(document).keydown(function(e) {
		    if (e.which == 39) { 
		       $('#show_element').click();
		       e.preventDefault();
		       return false;
		    }
		});


{% endblock %}


{% block header %}Vocabulary Practice{% endblock %}

{% block content %}
    <div class="top_left">
	    <a href="#">&laquo; Previous question</a>
    </div>
    <div class="top_right">
     	<a href="#" class="btn btn-primary" role="button">Next question &raquo;</a>
    </div>
{% endblock %}



{% block links %}
	<div class="text-center">
	   {% autoescape off %}{{ word_table }}{% endautoescape %}
	   <div id="translation" style="font-size:30px">
	       {% for string in extra_info %}
	           {{ string }}<br>
	       {% endfor %}
	   </div><br /><br />
	   <button id="show_element" class="btn btn-success btn-sm" role="button">show answer</button>
	</div>
{% endblock %}